version: '2'
services:
    arbitrage-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb arbitrage-mongodb-config
    arbitrage-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    arbitrage-mongodb-config:
        image: mongo:3.6.3
        container_name: arbitrage-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
